services:
  panel-backend:
    image: sc2pte/panel-backend:1.0.2308
    container_name: sc2pte-panel-backend
    hostname: panel-backend
    ports:
      - ${SC2PTE_NODE_PORT}:${SC2PTE_NODE_PORT}
    environment:
      NODE_ENV: production
      SC2PTE_NODE_PORT: 3001
      SC2PTE_SAS_URL: http://sas:3002
      SC2PTE_REDIS_ENABLE: true
      SC2PTE_REDIS_HOST: redis
      SC2PTE_REDIS_PORT: 6379
      SC2PTE_REDIS_CACHE_SEGMENT: sc2pte2
      SC2PTE_REDIS_TTL_SECS: 1800
      SC2PTE_CLOUDFLARE_ENABLE: true
      SC2PTE_BATTLENET_REGION: us
    depends_on:
      - mongodb
      - redis
      - sas
      - bas

  mongodb:
    image: mongo:4.4.15
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${SC2PTE_MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${SC2PTE_MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SC2PTE_MONGODB_PASSWORD}
    deploy:
      replicas: 1
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - ${SC2PTE_REDIS_PORT}:${SC2PTE_REDIS_PORT}

  sas:
    image: sc2pte/sc2-api-service:2.0.20
    container_name: sas
    hostname: sas
    restart: always
    ports:
      - 3002:3002
    environment:
      NODE_ENV: production
      SAS_APP_PORT: 3002
      SAS_BATTLENET_REGION: ${SC2PTE_BATTLENET_REGION}
      SAS_BATTLENET_CLIENT_ID: ${SC2PTE_BATTLENET_CLIENT_ID}
      SAS_BATTLENET_CLIENT_SECRET: ${SC2PTE_BATTLENET_CLIENT_SECRET}
      SAS_REDIS_ENABLE: true
      SAS_REDIS_HOST: ${SC2PTE_REDIS_HOST}
      SAS_REDIS_DB: 1
      SAS_BAS_URL: http://bas:3003
    depends_on:
      - redis
      - bas

  bas:
    image: sc2pte/bnet-auth-service:2.0.75
    container_name: bas
    restart: always
    hostname: bas
    ports:
      - 3003:3003
    environment:
      NODE_ENV: production
      BAS_APP_PORT: 3003
      BAS_BATTLENET_REGION: ${SC2PTE_BATTLENET_REGION}
      BAS_BATTLENET_CLIENT_ID: ${SC2PTE_BATTLENET_CLIENT_ID}
      BAS_BATTLENET_CLIENT_SECRET: ${SC2PTE_BATTLENET_CLIENT_SECRET}
      BAS_REDIS_ENABLE: true
      BAS_REDIS_HOST: ${SC2PTE_REDIS_HOST}
      BAS_REDIS_DB: 2
    depends_on:
      - redis

volumes:
  mongodb_data_container:
